name: SimpleBackpacks
version: 1.1
author: Wylarel
main: com.wylarel.simplebackpacks.Main
description: A Minecraft plugin that adds simple backpacks to vanilla Minecraft
api-version: 1.15

depend: []

commands:
  backpack:
    description: Open your backpack
    permission: backpackcommand.use
    usage: /backpack
    aliases: [bp]